### ISSUE TITLE
[BUG] TimeSeries _fill_before error when series.index.max < tmin

### ISSUE THREAD

**Issue by HenrikSpa** [pastas/pastas#431] opened 2022-10-06 17:20 UTC
Simulating with tmin that is a later date than maxium index date of a stress series results in an empty series being returned from here:

https://github.com/pastas/pastas/blob/1cd9fd94502920de8ae1bb03a902fd0d5ab25354/pastas/timeseries.py#L545-L546

This will cause an error in _fill_after here:

https://github.com/pastas/pastas/blob/1cd9fd94502920de8ae1bb03a902fd0d5ab25354/pastas/timeseries.py#L579-L580

The error:

```
....local/lib/python3.10/site-packages/pastas/timeseries.py", line 590, in _fill_after
    index_extend = pd.date_range(start=series.index.max(),
  File "/usr/lib/python3/dist-packages/pandas/core/indexes/datetimes.py", line 1097, in date_range
    dtarr = DatetimeArray._generate_range(
  File "/usr/lib/python3/dist-packages/pandas/core/arrays/datetimes.py", line 415, in _generate_range
    raise ValueError("Neither `start` nor `end` can be NaT")
ValueError: Neither `start` nor `end` can be NaT
```

Edit:
I should clarify that this happens in TimeSeries.update_series where _fill_before is called before _fill_after.

**Comment by rubencalje** [comment] 2022-10-07 07:07
Hi @HenrikSpa , I succeeded in reproducing the error with the following code:

```
import numpy as np
import pandas as pd
import pastas as pt
index_obs = pd.date_range('2018', '2020')
obs = pd.Series(np.random.rand(len(index_obs)), index=index_obs)
ml = pt.Model(obs)

index_stress = pd.date_range('2010', '2018')
stress = pd.Series(np.random.rand(len(index_stress)), index_stress)
sm = pt.StressModel(stress, pt.Gamma, 'test', settings='prec')
ml.add_stressmodel(sm)

ml.solve()
ml.simulate(tmin='2039')
```

The error happens when tmin minus the warmup period is not in the original series. I think we need to solve this.

**Comment by HenrikSpa** [comment] 2022-10-07 07:36
Great! But at the same time not great that you also had the error:) In my specific case it was a very short well series that caused it. I think that scenario is not that uncommon. I had to solve it by extending the well series with a flow of zero that covered the simulation period. 

And the problem itself happened when wanted to simulate the unsolved model using the initial parameters.

**Comment by raoulcollenteur** [comment] 2023-01-11 18:38
I am working on the TimeSeries object so I had a quick look into this. Here's the code I used to check the issue.

```
import numpy as np
import pandas as pd
import pastas as ps
index_obs = pd.date_range('2018', '2020')
obs = pd.Series(np.random.rand(len(index_obs)), index=index_obs)
series = ps.TimeSeries(obs, settings="prec")
series.update_series(tmin="2045")
```

But at least the last line should be the following because Pastas does not check if tmin < tmax (for now):

`series.update_series(tmin="2045", tmax="2055")`

fill_before is not necessary at all in this case, one could directly skip to fill_after. However, filling with the mean of the series (as when settings="prec") in fill_after would results in filling with nan-values because the mean of an empty series is nan. So the right way to do this is actually to do this manually as you did I think :) 

I think we could do the following:

- [ ] Throw an error when tmin > tmax, and while we're at it, tmax < tmin (catch such errors early), and when fill_after="mean". 

I need to think a bit more about this, not sure what would be the desired behaviour.

**Comment by raoulcollenteur** [comment] 2023-02-03 09:24
Closing this issue with a "wontfix" label. The code will now give an Error (see comment above, PR #523), but there are currently no plans to deal with tmin>series.index.max(). 

Thanks for opening the issue @HenrikSpa !

Cheers, Raoul

**Closed by raoulcollenteur** 2023-02-03 09:24 UTC
Labels: bug
