### ISSUE TITLE
Make private method private with leading underscore

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#74] opened 2018-06-12 15:55 UTC
I think we should make all non-public methods known by adding a leading underscore to the method name. This is suggested in PEP8 (https://www.python.org/dev/peps/pep-0008/), and is followed by all major packages (E.g. Numpy, Scipy, Pandas, Flopy). E.g. 

`Model._get_odelt()`

Also, we should not use private methods of other packages in Pastas, like the _base_and_stride taken from Pandas in utils.py. These methods can be dropped without notice, which can cause problems in future versions of Pastas.

This will make it more clear for the Pastas-users which methods they should use (They will pop up first on tab completion) and make maintenance of Pastas easier in the future.

Thoughts?

**Comment by Hugovdberg** [comment] 2018-06-13 08:53
There is actually a subtle difference between single and double underscores in front of the method name. Single underscore methods can be overriden by inherited objects (much like the `protected` keyword in other programming languages), while double underscore methods cannot be overridden.

Also, it isn't just part of PEP8, which just gives some basic style guides, and effectively says to use Python the way it was designed to be used. It is also part of the [Python Language Reference](https://docs.python.org/3/reference/lexical_analysis.html#reserved-classes-of-identifiers).

Using the underscores is an idiomatic way to keep the programming interface clean and keep flexibility in the implementation of the internals. As Raoul said most, if not all, major packages and programming tools respect and perhaps even expect this part of the language definition to be used.

I would definitely vote in favor of using the programming language's default method of what methods and functions are part of the external programming interface and what is not.

**Comment by pastas** [comment] 2018-06-13 11:32
Although Raoul and Hugo make good points, I think it is a pain in the butt
to use private methods with very little benefit. It rarely happens in
Pastas that anybody wants to call a function that they shouldn't. But that
is just my 5 cents.

**Comment by Hugovdberg** [comment] 2018-06-13 12:36
The problem is that it is unclear which methods they shouldn't use, except for the fact that they are marked as 'internal method' in the docstring.

I don't see how typing an underscore or two is a pain in the butt. What are the bad experiences you've had with private methods that make you think this way?

**Comment by Hugovdberg** [comment] 2018-07-05 21:20
Has anyone already started on making these interface changes? If not I hereby volunteer to implement this. I haven't heard compelling arguments against it so I'm assuming this is the way we want to go.

**Comment by mbakker7** [comment] 2018-07-06 11:04
My reason for not using private methods is that I don't see the advantage
while we are making things purposely obscure.

I don't think there is any problem now with people trying to access methods
that they shouldn't. So it doesn't solve a problem. So why 'hide' them now
(the are still discoverable and collable, btw, they are not invisible or
unaccessible). My suggestions is not to make anything private.

**Comment by raoulcollenteur** [comment] 2020-07-13 15:14
All methods of which the docstring starts with "Internal method..." will get a leading underscore in the next release.

**Comment by raoulcollenteur** [comment] 2020-07-22 15:16
To do:
- [ ] Add this to pastas code style page on the docs
- [ ] double-check throughout Pastas before closing this issue

**Closed** 2020-11-13 18:33 UTC
Labels: development
