### ISSUE TITLE
Double figures in Notebooks

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#51] opened 2017-10-03 10:48 UTC
It seems that the built-in plotting functionality of Pastas creates double figure instances when used in a IPython Notebook. A temporary fix can be to suppress output by adding a semi-colon, e.g.:

`ml.plots.decomposition();`
 Or by storing the returned figure instance:

`fig = ml.plots.decomposition()`

The methods keyword argument show=False has no effect in Notebooks.

Anyone knows how to solve this issue for all plotting methods?

**Comment by mbakker7** [comment] 2017-10-05 12:47
The problem is that, for example, `ml.plot()` returns a figure. As this figure is not stored, it is 'printed' to the screen, which means it is shown. If you add a semi-colon it is not shown (or if you store it in variable: `fig = ml.plot()`. Question is: why does the routine return the figure?

**Comment by raoulcollenteur** [comment] 2017-10-11 21:25
I just  did a commit to solve this issue. All plots now return the figure.axes 

Is this the way we want it?

There seems to be discussion on the pandas team as well: https://github.com/pandas-dev/pandas/issues/4020. The issue is still open..

**Comment by mbakker7** [comment] 2017-10-23 08:45
All plotting routines now return axes, which solves the problem and is consistent with what matplotlib does, so I close the issue.

**Closed by mbakker7** 2017-10-23 08:45 UTC
Labels: bug, help wanted
