### ISSUE TITLE
Model and Stressmodel should accept DataFrame with one column

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#71] opened 2018-06-12 14:18 UTC
If series is entered as DataFrame with one column, pastas should change it to a series

**Comment by raoulcollenteur** [comment] 2018-06-12 16:38
We had exactly this thing come up today during a workshop. I added this feature to the TimeSeries object. I did not document it, but Pastas can handle 1D DataFrames now.

**Comment by mbakker7** [comment] 2018-06-12 19:16
I just tried to use an oseries as a DataFrame, but it throws an error. 

`ml = ps.Model(ho)` 

gives

`AttributeError: 'DataFrame' object has no attribute 'name'`

and 

`ml = ps.Model(ho.head)` 

(which shouldn't be necessary) gives

`AttributeError: 'function' object has no attribute 'copy'`

**Comment by raoulcollenteur** [comment] 2018-06-12 21:38
The first error is apparently thrown because a pandas DataFrame does not have the attribute "name", which I did not know as pandas Series always have the name attribute. Maybe it best to make the user aware he/she is providing a DataFrame, and not deal with this in Pastas. It is quite some work to fix this, and future changes in DataFrames/Series can easily break the code so I would prefer sticking to only accepting Series and throwing an error when a DataFrame is provided.

The second attribute error is caused by using the pandas series method "head".. so that is outside of Pastas.

**Comment by Hugovdberg** [comment] 2018-06-13 08:31
Perhaps this could be solved using the `squeeze` method, which is available on both `DataFrame` and `Series`. By specifying the axis both should result in a `Series`.

**Comment by raoulcollenteur** [comment] 2018-06-13 09:22
This should work now, also when no name is provided as (e.g. ml = ps.Model(ho) instead of ml = ps.Model(ho, name="obs")). I think we can close this issue now.

**Comment by mbakker7** [comment] 2018-06-13 11:33
We have been using the squeeze method, just not inside Pastas. It seemed
like something we don't need to bother the user with.

**Comment by mbakker7** [comment] 2018-06-13 11:34
So does it work now when providing a DataFrame with 1 column?

I will test.

**Comment by mbakker7** [comment] 2018-06-13 16:52
It works now, but throws this warning:
WARNING: The provided series %s was a 1D DataFrame and was transformed to a pandas Series.

I don't see why we need a warning at all. But also, the %s is not correct. My vote is to remove the warning.

**Comment by raoulcollenteur** [comment] 2018-07-16 20:39
removed the warning, closing this issue.

**Closed by raoulcollenteur** 2018-07-16 20:39 UTC
Labels: enhancement
